jobs:
    include:
        -   language: php
            php:
                - '8.0'
            script:
                - cd backend
                - composer install
                - make ci

        -   language: node_js
            node_js: 14
            script:
                - cd frontend
                - yarn install
                - make ci
